# Generated by Django 5.2.17 on 2026-09-29 09:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_code', models.CharField(help_text='Anonymized ID e.g. PAT-2026-001', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('occupation', models.CharField(max_length=150)),
                ('residence_area', models.CharField(help_text='City, area or neighborhood', max_length=150)),
                ('diagnosis_type', models.CharField(choices=[('MI', 'Myocardial Infarction / Heart Attack'), ('STROKE', 'Ischemic / Hemorrhagic Stroke'), ('BOTH', 'Both Heart Attack & Stroke')], max_length=10)),
                ('blood_pressure_systolic', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, null=True)),
                ('ejection_fraction_pct', models.DecimalField(blank=True, decimal_places=1, help_text='Echo EF %', max_digits=4, null=True)),
                ('lifestyle_data', models.JSONField(blank=True, default=dict)),
                ('dietary_data', models.JSONField(blank=True, default=dict)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
