# Generated by Django 5.2.17 on 2026-09-29 09:40

import apps.reports.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('ECG', 'Electrocardiogram'), ('ECHO', 'Echocardiogram'), ('EEG', 'Electroencephalogram'), ('LIPID', 'Lipid Profile Lab'), ('BLOOD', 'Other Blood Test Report'), ('OTHER', 'General Medical Document')], max_length=20)),
                ('title', models.CharField(blank=True, help_text='e.g. Admission ECG, 24h Echo', max_length=255)),
                ('file', models.FileField(upload_to=apps.reports.models.patient_report_upload_path)),
                ('notes', models.TextField(blank=True, help_text='Notes taken by intern doctor', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
