# Generated by Django 5.2.17 on 2026-09-29 09:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreetFoodOilSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sample_tag_code', models.CharField(help_text='e.g. OIL-PAT001-A', max_length=50, unique=True)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('vendor_location', models.CharField(help_text='Street address or area of food stall', max_length=255)),
                ('food_item_type', models.CharField(help_text='e.g. Fried Chicken, Singara, Puri', max_length=150)),
                ('collected_at', models.DateField(auto_now_add=True)),
                ('trans_fat_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peroxide_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('lab_analysis_notes', models.TextField(blank=True, null=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oil_samples', to='patients.patient')),
            ],
        ),
    ]
